version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - db_test
    volumes:
      - ..:/workspace:cached
    command: /bin/sh -c "while sleep 1000; do :; done"

  db_test:
    image: postgres:latest
    environment:
      POSTGRES_USER: cicd
      POSTGRES_PASSWORD: web_compiler
      POSTGRES_DB: web_compiler_test
    ports:
      - "34837:5432"
