name: Elixir CI

on:
  push:
    branches: [ main ]
  pull_request:

concurrency: 
  group: ${{ github.workflow }}-${{ github.event_name == 'push' && github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v2

    - name: Setup Environment
      run: |
        sudo apt-get update
        sudo apt-get install -y curl g++-14-riscv64-linux-gnu git cmake mold software-properties-common
        sudo add-apt-repository ppa:rabbitmq/rabbitmq-erlang
        sudo apt update
        sudo apt install -y elixir erlang-dev erlang-xmerl

    - name: Install Rust
      run: |
        curl https://sh.rustup.rs -sSf | sh -s -- -y
        echo "/root/.cargo/bin" >> $GITHUB_PATH
        rustup default nightly
        rustup target add riscv64gc-unknown-linux-gnu

    - name: Install Dependencies
      run: |
        mix local.hex --force
        mix local.rebar --force
        mix deps.get

    - name: Run Tests
      run: mix test
